apiVersion: apps/v1
kind: Deployment
metadata:
  name: sistema-estrellas
  labels:
    app: sistema-estrellas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      env: dev
  template:
    metadata:
      labels:
        app: frontend
        env: dev
    spec:
      volumes:
        - name: kc-config
          configMap:
            name: realm-config

      containers:
        - name: frontend
          image: abd-tc01-frontend
          imagePullPolicy: Never
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 300m
              memory: 2048Mi
          ports:
            - containerPort: 5173
          envFrom:
            - configMapRef:
                name: app-env
          env:
            - name: VITE_BACKEND_ROUTE
              value: $(BASE_URI):$(BACKEND_PORT)
            - name: VITE_AUTHORITY
              value: $(BASE_URI):$(KEYCLOAK_PORT)/realms/$(REALM_NAME)
            - name: VITE_CLIENT_ID
              value: $(CLIENT_ID)
            - name: VITE_TIMEOUT_TIME
              value: $(TIMEOUT_TIME)

        - name: keycloak
          image: quay.io/keycloak/keycloak:26.7.0
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 300m
              memory: 2048Mi
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-env
          env:
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: $(KEYCLOAK_ADMIN_USERNAME)
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              value: $(KEYCLOAK_ADMIN_PASSWORD)
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_HTTP_MANAGEMENT_PORT
              value: $(KEYCLOAK_MANAGEMENT_PORT)
            - name: REALM_NAME
              value: $(REALM_NAME)
            - name: CLIENT_ID
              value: $(CLIENT_ID)
            - name: BASE_URL
              value: $(BASE_URI):$(REACT_PORT)
          args: ["start-dev", "--import-realm"]
          volumeMounts:
            - name: kc-config
              mountPath: /opt/keycloak/data/import/
