services:

  #frontend:

  #backend:

  database: 
    image: postgres:17-alpine
    
    container_name: mi-postgresito
    environment:
      - POSTGRES_USER: ${POSTGRES_USER}
      - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      - POSTGRES_DB: ${POSTGRES_DB}
    #volumes:
      ## mas tarde
    ports:
      - "${DB_PORT}:${POSTGRE_INTERNAL_PORT}"
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 1m10s
      timeout: 30ss
      retries: 5
      start_period: 30s


  #keycloak:

  #Kubernates:


#volumes:
  
