apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deploy/frontend/deployment.yaml
  - deploy/frontend/service.yaml
  - deploy/keycloak/deployment.yaml
  - deploy/keycloak/service.yaml
  - deploy/backend/deployment.yaml
  - deploy/backend/service.yaml
  - deploy/database/deployment.yaml
  - deploy/database/service.yaml

configMapGenerator:
  - name: app-env
    envs:
      - .env
  - name: realm-config
    files:
      - ./keycloak/realm-export.json
  - name: env-config
    files:  
      - .env
  - name: db-init
    files:
      - ./database/init_db.sql
      
