apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./k8s/base/frontend/deployment.yaml
  - ./k8s/base/frontend/service.yaml
  - ./k8s/base/keycloak/deployment.yaml
  - ./k8s/base/keycloak/service.yaml
  - ./k8s/base/backend/deployment.yaml
  - ./k8s/base/backend/service.yaml
  - ./k8s/base/database/deployment.yaml
  - ./k8s/base/database/service.yaml
  - ./k8s/base/database/pvc.yaml
  
configMapGenerator:
  - name: app-env
    envs:
      - .env
  - name: realm-config
    files:
      - ./keycloak/realm-export.json
  - name: env-config
    files:
      - .env
  - name: db-init
    files:
      - ./database/init_db.sql
