services:

  db:
    image: postgres:17-alpine
    container_name: Tarea1-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d:ro
    
    ports:
       - "${DB_PORT}:${POSTGRE_INTERNAL_PORT}"
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  keycloak:
    image: quay.io/keycloak/keycloak:26.7.0
    container_name: keycloak
    command: start-dev --import-realm  #para que keycloak revise el realm antes de arrancar
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}

    ports:
      - "${KEYCLOAK_PORT}:${KEYCLOAK_INTERNAL_PORT}"  #todo puerto con variable de entorno

    #Monta el realm parque que keycloak lo importe automaticamente
    #Evita tener que crear el realm manualmente en cada computadora
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json

volumes:
  pgdata:



 
