apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: frontend
  ports:
    - name: frontend-service-port
      protocol: TCP
      port: 5173
      targetPort: frontend-port
      nodePort: 30080
